/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "day.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

time_out *
gettime_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static time_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GETTIME, xdr_void, argp, xdr_time_out, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
